# -*- coding: utf-8 -*-
"""task_5_ds_intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mY_XavnQ77gMFDelbdXwT3Z2DryiCRVP

*TASK 5 : Analyze traffic accident data to identify patterns related to road conditions, weather, and time of day. Visualize accident hotspots and contributing factors.*
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_excel('road_accident_bangladesh_1980_2023.xlsx')
data.head()

"""**COUNT ANALYSIS OF ACCIDENTS BY YEAR IN BANGLADESH**"""

plt.figure(figsize=[7,3])

sns.lineplot(y=data['Number of Accidents'],x=data['Year'],color='Red',ls='dashed')
plt.title('Count Analysis of Accidents by Year in Bangaldesh')
plt.xlim(1980,2025)
plt.ylim(0,1800)
plt.show()

"""**ROAD ACCIDENT ANALYSIS BY LEVEL OF SEVERITY IN BANGLADESH**"""

import numpy as np

bar_width = 0.25
index = np.arange(len(data['Year']))
plt.figure(figsize=[20,5])
# Plotting the bars
plt.bar(index, data['Number of Minor Injuries'], bar_width, label='Minor Injuries')
plt.bar(index + 2*bar_width, data['Number of Severe Injuries'], bar_width, label='Severe Injuries')

plt.xlabel('Year')
plt.ylabel('Number of Injuries')
plt.title('Road Accident Injuries by Severity (1980-2023)')
plt.xticks(index + bar_width, data['Year'])
plt.legend()

plt.tight_layout()
plt.show()

"""**ACCIDENT INSIGHTS FROM THE PAST 6 YEARS IN BANGLADESH**"""

df=data[data['Year'].between(2019,2023)]
df=pd.DataFrame(df)
df

"""**COUNT OF DEATH DISTRIBUTION (2019 - 2023)**"""

plt.figure(figsize=(7,7))
colors_pie= ['gold', 'lightcoral', 'lightskyblue', 'lightgreen', 'orange']

plt.pie(df['Death'], labels=df['Year'], autopct='%.0f%%', startangle=90,colors=colors_pie)

plt.title('Distribution of Death Counts by Year (2019-2023)')
plt.axis('equal')
plt.show()